AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation - Networking
Parameters:
  InfraCode:
    Type: String
  VpcCIDR:
    Type: String
#  VpcName:
#    Type: String
#  InternetGatewayName:
#    Type: String
  PublicSubnet1CIDR:
    Type: String
#  PublicSubnet1Name:
#    Type: String
  PublicSubnet2CIDR:
    Type: String
#  PublicSubnet2Name:
#    Type: String
  PrivateSubnet1CIDR:
    Type: String
#  PrivateSubnet1Name:
#    Type: String
  PrivateSubnet2CIDR:
    Type: String
#  PrivateSubnet2Name:
#    Type: String
#  NatGatewayName:
#    Type: String
#  PublicRouteTableName:
#    Type: String
#  PrivateRouteTableName:
#    Type: String


Resources:
  # ====================================
  # Networking: VPC, subnets
  # ====================================
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${InfraCode}-vpc"
          #Value: !Ref VpcName

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVpc
      CidrBlock: !Ref PublicSubnet1CIDR
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${InfraCode}-pub-subnet1"
        #  Value: !Ref PublicSubnet1Name

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVpc
      CidrBlock: !Ref PublicSubnet2CIDR
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${InfraCode}-pub-subnet2"
        #  Value: !Ref PublicSubnet2Name
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVpc
      CidrBlock: !Ref PrivateSubnet1CIDR
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${InfraCode}-priv-subnet1"
        #  Value: !Ref PrivateSubnet1Name

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVpc
      CidrBlock: !Ref PrivateSubnet2CIDR
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${InfraCode}-priv-subnet2"
        #  Value: !Ref PrivateSubnet2Name


Outputs:
  VPCId:
    Value: !Ref MyVpc
    Description: ID of the VPC
  #  Export:
  #    Name: !Sub "${AWS::StackName}-vpc"
  PublicSubnetId1:
    Value: !Ref PublicSubnet1
    Description: Public subnet ID
  #  Export:
  #    Name: !Sub "${AWS::StackName}-pub-subnet1"
  PublicSubnetId2:
    Value: !Ref PublicSubnet2
    Description: Public subnet ID
  #  Export:
  #    Name: !Sub "${AWS::StackName}-pub-subnet2"
  PrivateSubnetId1:
    Value: !Ref PrivateSubnet1
    Description: Private subnet ID
  #  Export:
  #    Name: !Sub "${AWS::StackName}-priv-subnet1"
  PrivateSubnetId2:
    Value: !Ref PrivateSubnet2
    Description: Private subnet ID
  #  Export:
  #    Name: !Sub "${AWS::StackName}-priv-subnet2"