AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation - Cluster
Parameters:
  InfraCode:
    Type: String
  EnvName:
    Type: String
#  ClusterName:
#    Type: String
#    Description: ECS Cluster Name
Resources:
  # =====================
  # ECS Cluster
  # =====================
  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      #ClusterName: !Ref ClusterName
      ClusterName: !Sub "${InfraCode}-${EnvName}"

Outputs:
  ECSClusterId:
    Value: !Ref MyECSCluster
    Description: ECS Cluster