AWSTemplateFormatVersion: '2010-09-09'
Description: IFM CloudFormation - S3
Parameters:
  InfraCode:
    Type: String
#  S3Bucketname:
#    Type: String

Resources:
  # ========================================
  # S3
  # ========================================
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      #BucketName: !Ref S3Bucketname
      BucketName: !Sub "${InfraCode}-bucket"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced # Ensures bucket owner owns all objects
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true


Outputs:
  S3RegionalDomainName:
    Value: !GetAtt S3Bucket.RegionalDomainName
    Description: Region-specific endpoint of S3 bucket
  S3Arn:
    Value: !GetAtt S3Bucket.Arn
    Description: S3 bucket ARN
