AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation - Log Group
Parameters:
  InfraCode:
    Type: String
#  ECSLogGroupName:
#    Type: String
#    Description: Log group name of ECS container
#  ServiceName:
  ECSContainerName:
    Type: String

  ECSLogGroupRetention:
    Type: Number

  EnvName:
    Type: String
Resources:
  # =====================
  # Log Group
  # =====================
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      #LogGroupName: !Ref ECSLogGroupName
      LogGroupName: !Sub "${InfraCode}/${EnvName}/${ECSContainerName}-log"
      RetentionInDays: !Ref ECSLogGroupRetention

Outputs:
  LogGroupId:
    Value: !Ref LogGroup
    Description: Log Group ID
