AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation - CloudFront
Parameters:
  InfraCode:
    Type: String
#  CloudFrontOACName:
#    Type: String

  CloudFrontOriginPath:
    Type: String
  ApiGatewayDomainName:
    Type: String
  S3RegionalDomainName:
    Type: String

Resources:
  # ========================================
  # CloudFront
  # ========================================

  MyCloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        #Name: !Ref CloudFrontOACName
        Name: !Sub "${InfraCode}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: Access control for CloudFront to S3

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        Origins:
          - Id: S3Origin
            #DomainName: !GetAtt S3Bucket.RegionalDomainName
            DomainName: !Ref S3RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref MyCloudFrontOAC
          - Id: ApiGatewayOrigin
            #DomainName: !Sub ${MyApiGateway}.execute-api.${AWS::Region}.amazonaws.com
            DomainName: !Ref ApiGatewayDomainName
            OriginPath: !Ref CloudFrontOriginPath
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: '403'
            ResponsePagePath: /index.html
            ResponseCode: '200'
            ErrorCachingMinTTL: '0'
          - ErrorCode: '404'
            ResponsePagePath: /index.html
            ResponseCode: '200'
            ErrorCachingMinTTL: '0'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - DELETE
            - POST
            - OPTIONS
            - PUT
            - PATCH
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
            Headers:
              - Origin
          DefaultTTL: 86400 # 1 day
          MinTTL: 3600 # 1 hour
          MaxTTL: 31536000 # 1 year
        CacheBehaviors:
          - PathPattern: api/*
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: allow-all
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Headers:
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
                - Origin
                - Authorization
            Compress: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  CloudFrontURL:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: CloudFront URL for S3 content
  CloudFrontId:
    Value: !Ref CloudFrontDistribution
    Description: CloudFront ID