name: 'Deploy CloudFormation Stack'
description: 'Reusable action to deploy a CloudFormation stack'
inputs:
  stack-name:
    required: true
  template-file:
    required: true
  parameter-file:
    required: true
runs:
  using: "composite"
  steps:
    - name: Deploy CloudFormation stack
      shell: bash
      run: |
        aws cloudformation deploy \
          --template-file ${{ inputs.template-file }} \
          --stack-name ${{ inputs.stack-name }} \
          --parameter-overrides file://${{ inputs.parameter-file }} \
          --capabilities CAPABILITY_NAMED_IAM