name: "AWS Configure"
description: "Configure AWS credentials"

inputs:
  aws-region:
    required: true
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        #role-to-assume: 
        access-key-id: ${{ inputs.aws-access-key-id }}
        secret-access-key: ${{ inputs.aws-secret-access-key }}
        region: ${{ inputs.aws-region }}
