name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  #STACK_NAME: infrastructure-stack
  ENV_NAME: dev
  PARAMS_FILE: aws-cloudformation/parameters/dev.json
  VPC_TEMPLATE: aws-cloudformation/templates/aws-networking.yaml
  SG_TEMPLATE: aws-cloudformation/templates/aws-sg.yaml
  ALB_TEMPLATE: aws-cloudformation/templates/aws-ecs-loadbalancer.yaml
  APIG_TEMPLATE: aws-cloudformation/templates/aws-apigateway.yaml
  S3_TEMPLATE: aws-cloudformation/templates/aws-s3-cf.yaml
  CF_TEMPLATE: aws-cloudformation/templates/aws-cloudfront.yaml
  S3_POLICY_TEMPLATE: aws-cloudformation/templates/aws-s3-policy.yaml
  ECR_TEMPLATE: aws-cloudformation/templates/aws-ecr.yaml
  LOG_GROUP_TEMPLATE: aws-cloudformation/templates/aws-ecs-loggroup.yaml
  ECS_ROLE_TEMPLATE: aws-cloudformation/templates/aws-ecs-role.yaml
  ECS_CLUSTER_TEMPLATE: aws-cloudformation/templates/aws-ecs-cluster.yaml
  ECS_SERVICE_TEMPLATE: aws-cloudformation/templates/aws-ecs-service.yaml
  ECS_TD_TEMPLATE: aws-cloudformation/templates/aws-ecs-taskdefinition.yaml
  

jobs:
  validate_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install cfn-lint dependencies
        run: |
          # Install cfn-lint
          python3 -m pip install --upgrade pip
          pip3 install cfn-lint
          cfn-lint --version

      - name: Lint CloudFormation templates
        run: |
          for template in aws-cloudformation/templates/*.yaml; do
            echo "Linting $template"
            cfn-lint -t "$template" 
          done
          


  deploy_network:
    runs-on: ubuntu-latest
    needs: validate_files
    #outputs:
    #  network_outputs: ${{ steps.network.outputs.outputs-json }}
    outputs:
      vpc_name: ${{ steps.network_output.outputs.VPCId }}
      public_subnet1: ${{ steps.network.outputs.PublicSubnetId1 }}
      public_subnet2: ${{ steps.network.outputs.PublicSubnetId2 }}
      private_subnet1: ${{ steps.network.outputs.PrivateSubnetId1 }}
      private_subnet2: ${{ steps.network.outputs.PrivateSubnetId2 }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy CloudFormation Stack - Networking
        id: network
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-network
          template-file: ${{ env.VPC_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
          output-keys: VPCId,PublicSubnetId1,PublicSubnetId2,PrivateSubnetId1,PrivateSubnetId2

  deploy_sg:
    runs-on: ubuntu-latest
    needs: deploy_network
    outputs:
      sg_ecs_id: ${{ steps.security_group_output.outputs.SecurityGroupEcsId }}
      sg_alb_id: ${{ steps.security_group_output.outputs.SecurityGroupAlbId }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}      
      - name: Deploy CloudFormation Stack - Security Group
        id: security_group
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-security-group
          template-file: ${{ env.SG_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
          extra-params: |
            VPCId=${{ needs.deploy_network.outputs.vpc_name }}
          output-keys: SecurityGroupEcsId,SecurityGroupAlbId
        #  parameters: >-
        #    VPCId=$(echo '${{ needs.deploy_network.outputs.network_outputs }}' | jq -r '.[]|select(.OutputKey=="VPCId").OutputValue')
      
      
  deploy_alb:
    runs-on: ubuntu-latest
    needs: [deploy_network, deploy_sg]
    outputs:
      alb_dns_name: ${{ steps.alb_output.outputs.AppLoadBalancerDnsName }}
      alb_target_group: ${{ steps.alb_output.outputs.AppLoadBalancerTargetGroupId }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy CloudFormation Stack - Application Load Balancer
        id: alb
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-alb
          template-file: ${{ env.ALB_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
          extra-params: |
            VPCId=${{ needs.deploy_network.outputs.VPCId }}
            PublicSubnetId1=${{ needs.deploy_network.outputs.PublicSubnetId1 }}
            PublicSubnetId2=${{ needs.deploy_network.outputs.PublicSubnetId2 }}
            SecurityGroupAlbId=${{ needs.deploy_network.outputs.SecurityGroupAlbId }}
          output-keys: AppLoadBalancerDnsName,AppLoadBalancerTargetGroupId


  deploy_api-gateway:
    runs-on: ubuntu-latest
    needs: deploy_alb
    outputs:
      api_gateway_id: ${{ steps.api_gateway_output.outputs.ApiGatewayId }} \
      api_gateway_domain_name: ${{ steps.api_gateway_output.outputs.ApiGatewayDomainName }}


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy CloudFormation Stack - API Gateway
        id: apig
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-api-gateway
          template-file: ${{ env.APIG_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
		      extra-params: |
            AppLoadBalancerDnsName=${{ needs.deploy_alb.outputs.alb_dns_name }}
          output-keys: ApiGatewayId,ApiGatewayDomainName



  deploy_s3:
    runs-on: ubuntu-latest
    needs: validate_files
    #env:
    #  PARAMS_FILE: aws-cloudformation/parameters/dev.json
    outputs:
      s3_regional_domain_name: ${{ steps.s3_output.outputs.S3RegionalDomainName }}
      s3_arn: ${{ steps.storage.outputs.S3Arn }}
      s3_id: ${{ steps.storage.outputs.S3BucketId }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        #uses: aws-actions/configure-aws-credentials@v2
        uses: ./.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy CloudFormation Stack - S3 Bucket
        id: storage
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-storage
          template-file: ${{ env.S3_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
          output-keys: S3RegionalDomainName,S3Arn,S3BucketId


  deploy_cloudfront:
    runs-on: ubuntu-latest
    needs: [deploy_api-gateway, deploy_s3]
    outputs:
      cloudfront_url: ${{ steps.cloudfront.outputs.CloudFrontURL }} \
      cloudfront_id: ${{ steps.cloudfront.outputs.CloudFrontId }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy CloudFormation Stack - Cloudfront
        id: cloudfront
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-cloudfront
          template-file: ${{ env.CF_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
		      extra-params: |
            S3RegionalDomainName=${{ needs.deploy_s3.outputs.s3_regional_domain_name }}
            ApiGatewayDomainName=${{ needs.deploy_api-gateway.outputs.api_gateway_domain_name }}
          output-keys: CloudFrontURL,CloudFrontId
    


  deploy_s3-policy:
    runs-on: ubuntu-latest
    needs: [deploy_s3, deploy_cloudfront]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy CloudFormation Stack - S3 Bucket Policy
        id: s3-policy
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-s3-policy
          template-file: ${{ env.S3_POLICY_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
		      extra-params: |
            S3BucketId=${{ needs.deploy_s3.outputs.s3_id }}
            S3Arn=${{ needs.deploy_s3.outputs.s3_arn }}
            CloudFrontId=${{ needs.deploy_cloudfront.outputs.cloudfront_id }}
          output-keys: VPCId,PublicSubnetId1


  deploy_ecr:
    runs-on: ubuntu-latest
    needs: validate_files
    outputs:
      ecr_repository_name: ${{ steps.ecr.outputs.EcrRepositoryName }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation Stack - ECR
        id: ecr
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-ecs-ecr
          template-file: ${{ env.ECR_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
		      extra-params: |
            ENV_NAME=${{ env.ENV_NAME }}
          output-keys: EcrRepositoryName

  
  deploy_ecr_docker_image:
    runs-on: ubuntu-latest
    needs: deploy_ecr
    outputs:
      image_uri: ${{ steps.docker_image_build_output.outputs.image_uri }}
    #  task_definition_id: ${{ steps.ecs_taskdefinition_output.outputs.task_definition_id }}
    #env:
    #  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    #  IMAGE_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        id: docker_image_build_output
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
          ECR_REPO_NAME: ${{ needs.deploy_ecr.outputs.ecr_repository_name }}
        run: |
          IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
          echo "image_uri=$IMAGE_URI" >> "$GITHUB_OUTPUT"
          echo "IMAGE_URI=$IMAGE_URI" >> "$GITHUB_ENV"
          echo "Building image: $IMAGE_URI"
          docker build -t $IMAGE_URI:latest microservice/app

        #  REPO_NAME=${{ needs.deploy_ecs-req.outputs.ecr_repository_name }}
        #  REGION=${{ env.AWS_REGION }}
        #  ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        #  IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:latest

      - name: Push Docker image to ECR
        run: |
          docker push $IMAGE_URI:latest
        # echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

        #  REPO_NAME=my-ecr-repo
        #  REGION=${{ env.AWS_REGION }}
        #  ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        #  IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:latest


  deploy_ecs-req:
    runs-on: ubuntu-latest
    needs: [deploy_api-gateway]
    outputs:
      loggroup_id: ${{ steps.ecs-loggroup.outputs.LogGroupId }} \
      ecs_role_arn: ${{ steps.ecs_role.outputs.EcsRoleArn }} \
      ecs_cluster_id: ${{ steps.ecs.outputs.ECSClusterId }}
      #ecr_repository_name: ${{ steps.ecr_output.outputs.ecr_repository_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy CloudFormation Stack - ECS Log Group
        env:
          ENV_NAME: ${{ env.ENV_NAME }}
        id: ecs-loggroup
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-ecs-loggroup
          template-file: ${{ env.LOG_GROUP_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
		      extra-params: |
            EnvName=$ENV_NAME
            ServiceName=${{ needs.deploy_api-gateway.outputs.api_gateway_domain_name }}
          output-keys: LogGroupId


      - name: Deploy CloudFormation Stack - ECS Role
        id: ecs-role
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-ecs-role
          template-file: ${{ env.CF_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
          output-keys: ECS_ROLE_ARN


      - name: Deploy CloudFormation Stack - ECS Cluster
        env:
          ENV_NAME: ${{ env.ENV_NAME }}
        id: ecs
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-ecs-cluster
          template-file: ${{ env.ECS_CLUSTER_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
		      extra-params: |
            EnvName=$ENV_NAME
          output-keys: ECSClusterId


  deploy_ecs-microservice:
    runs-on: ubuntu-latest
    needs: [deploy_ecr, deploy_ecr_docker_image, deploy_ecs-req, deploy_alb, deploy_network, deploy_sg]
    outputs:
      task_definition_id: ${{ steps.ecs_taskdefinition_output.outputs.task_definition_id }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: /.github/actions/aws-config
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}            
      - name: Deploy CloudFormation Stack - ECS Task Definition
        id: ecs-taskdefinition
        env:
          env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
          ECR_REPO_NAME: ${{ needs.deploy_ecr.outputs.ecr_repository_name }}
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-ecs-taskdefinition
          template-file: ${{ env.ECS_TD_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
		      extra-params: |
            LogGroupId=${{ needs.deploy_ecs-req.outputs.loggroup_id }}
            EcsRoleArn=${{ needs.deploy_ecs-req.outputs.ecs_role_arn }}
            ContainerImage=${{ needs.deploy_ecr_docker_image.outputs.image_uri }}
          output-keys: TaskDefinitionId


      - name: Deploy CloudFormation Stack - ECS Service
        id: ecs-service
        uses: ./.github/actions/deploy-cf-stack
        with:
          stack-name: ${{ env.ENV_NAME }}-ecs-service
          template-file: ${{ env.ECS_SERVICE_TEMPLATE }}
          params-file: ${{ env.PARAMS_FILE }}
		      extra-params: |
            ECSClusterId=${{ needs.deploy_ecs-req.outputs.ecs_cluster_id }}
            TaskDefinitionId=${{ steps.ecs_taskdefinition_output.outputs.task_definition_id }}
            AppLoadBalancerTargetGroupId=${{ needs.deploy_alb.outputs.alb_target_group }}
            PrivateSubnetId1=${{ needs.deploy_network.outputs.private_subnet1 }}
            PrivateSubnetId2=${{ needs.deploy_network.outputs.private_subnet2 }}
            SecurityGroupEcsId=${{ needs.deploy_sg.outputs.sg_ecs_id }}






        run: |
          PARAMS=$(jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' ${{ env.PARAMS_FILE }})
          aws cloudformation deploy \
            --template-file aws-cloudformation/templates/aws-ecs-service.yaml \
            --stack-name ${{ env.ENV_NAME }}-ecs-service \
            --parameter-overrides \
              ECSClusterId=${{ needs.deploy_ecs-req.outputs.ecs_cluster_id }} \
              TaskDefinitionId=${{ steps.ecs_taskdefinition_output.outputs.task_definition_id }} \
              AppLoadBalancerTargetGroupId=${{ needs.deploy_alb.outputs.alb_target_group }} \
              PrivateSubnetId1=${{ needs.deploy_network.outputs.private_subnet1 }} \
              PrivateSubnetId2=${{ needs.deploy_network.outputs.private_subnet2 }} \
              SecurityGroupEcsId=${{ needs.deploy_sg.outputs.sg_ecs_id }} \
              $PARAMS

         